# Generated by Django 5.0.3 on 2024-05-19 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_image_url_alter_post_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='react',
            unique_together={('post', 'user')},
        ),
    ]
